# Generated by Django 2.2.12 on 2020-04-19 02:16

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_auto_20200418_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commendation_Coverage', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Abuja', 'Abuja'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Enugu', 'Enugu'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara'), ('National Coverage', 'National Coverage')], max_length=100)),
                ('Commendation_Title', models.CharField(max_length=100)),
                ('Commendation_Category', models.CharField(choices=[('Corporate Accountability', 'Corporate Accountability'), ('Corruption', 'Corruption'), ('Entertainment', 'Entertainment'), ('Environment', 'Environment'), ('Governance', 'Governance'), ('Health', 'Health'), ('Judiciary', 'Judiciary'), ('Media, Arts and Culture', 'Media, Arts and Culture'), ('Power Electricity', 'Power Electricity'), ('Politic, Election', 'Politic, Election'), ('Road and Transport', 'Road and Transport'), ('Safety and Security', 'Safety and Security'), ('Others', 'Others')], max_length=100)),
                ('Commendation_Category_Other', models.CharField(blank=True, max_length=100)),
                ('Action_Person', models.CharField(max_length=100)),
                ('Action_Person_Other', models.CharField(blank=True, max_length=100)),
                ('Expalnation', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Image', models.ImageField(blank=True, upload_to='')),
                ('approve', models.BooleanField(blank=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
