# Generated by Django 2.2.12 on 2020-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_commendationresponsefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='golbal_Admin',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3),
        ),
    ]
