# Generated by Django 2.2.12 on 2020-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_petitionresponsefeedback_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='commendationresponsefeedback',
            name='response',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='False', max_length=6),
        ),
        migrations.AlterField(
            model_name='petitionresponsefeedback',
            name='response',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='False', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='golbal_Admin',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='False', max_length=6),
        ),
    ]
