# Generated by Django 2.2.12 on 2020-04-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200421_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='commendation',
            name='Action_Person',
            field=models.CharField(choices=[('President', 'President'), ('Minister', 'Minister'), ('Senate', 'Senate'), ('State Governor', 'State Governor'), ('State Assembly', 'State Assembly'), ('Local Gov. Chairman', 'Local Gov. Chairman'), ('Others', 'Others')], max_length=100),
        ),
    ]
