# Generated by Django 2.2.12 on 2020-04-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200421_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedManager',
        ),
    ]
