# Generated by Django 2.2.12 on 2020-04-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_petition_signer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition_signer',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
