# Generated by Django 2.2.12 on 2020-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200425_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aggreeTerms',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
