# Generated by Django 2.2.12 on 2020-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_userprofile_aggreeterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='approve',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
