# Generated by Django 2.2.12 on 2020-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20200503_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Question')),
                ('answers', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Answers')),
            ],
        ),
        migrations.AlterField(
            model_name='commendationresponsefeedback',
            name='response',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No'), (None, 'None')], default='False', max_length=6),
        ),
        migrations.AlterField(
            model_name='petitionresponsefeedback',
            name='response',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No'), (None, 'None')], default=None, max_length=6),
        ),
    ]
