# Generated by Django 2.2.12 on 2020-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20200505_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedquestions',
            name='category',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Category'),
        ),
    ]
