# Generated by Django 2.2.12 on 2020-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_askedquestions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquestions',
            name='category',
            field=models.CharField(choices=[('Account', 'Account'), ('Petition', 'Petition'), ('Commendation', 'Commendation'), ('Donation', 'Donation'), ('Blog', 'Blog'), ('Others', 'Others')], default='Others', max_length=20, null=True, verbose_name='Category'),
        ),
    ]
