# Generated by Django 2.2.12 on 2020-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_webbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbanner',
            name='banner',
            field=models.ImageField(height_field=350, upload_to='Banner/%y/%m/%d/', verbose_name='Banner', width_field=1920),
        ),
    ]
