# Generated by Django 2.2.12 on 2020-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20200506_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbanner',
            name='banner',
            field=models.ImageField(upload_to='Banner/%y/%m/%d/', verbose_name='Banner'),
        ),
    ]
