# Generated by Django 2.2.12 on 2020-05-06 10:28

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20200506_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbanner',
            name='banner',
            field=models.ImageField(upload_to='Banner/%y/%m/%d/', validators=[mysite.models.validate_image], verbose_name='Banner'),
        ),
    ]
