# Generated by Django 2.2.12 on 2020-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20200506_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commendation',
            name='approve',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
