# Generated by Django 2.2.12 on 2020-05-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200422_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
